name: KineshmaApp
description: "RaspisanieKineshma"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.2.0
  auto_route: ^10.0.1
  crypto: ^3.0.6
  dio: ^5.8.0+1
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  timelines_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo/logo.jpg"
  macos:
    generate: true
    image_path: "assets/logo/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: TTSmalls-SemiBold
      fonts:
        - asset: assets/fonts/TTSmalls-SemiBold.ttf
    - family: Century_Gothic
      fonts:
        - asset: assets/fonts/Century_Gothic.ttf
    - family: Franklin_Gothic_Medium
      fonts:
        - asset: assets/fonts/Franklin_Gothic_Medium.ttf